### ISSUE TITLE
[bug]: FTP Instances are not enabled once created. 

### ISSUE THREAD

**Issue by danardf** [FreePBX/filestore#20]
### FreePBX Version

FreePBX 16

### Issue Description

https://sangomakb.atlassian.net/wiki/spaces/PG/pages/25788491/Filestore+Module+GraphQL+APIs

There is no way to enable any FTP instances once created. So, after creating one, the FTP instance is not displayed. That means we can't enable it through API GQL. 

I will raise a PR to fixe this issue adding **enabled: yes / no** 

### Operating Environment

filestore           | 17.0.2.21
filestore           | 16.0.18

**Comment by kapilgupta01** [comment]
filestore v16.0.18.1
filestore v17.0.2.22

**Comment by danardf** [comment]
@kguptasangoma Thanks
